// Copyright 2016 MongoDB Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// src/mangrove/config/compiler.hpp
#pragma push_macro("MANGROVE_INLINE")
#undef MANGROVE_INLINE
#pragma push_macro("MANGROVE_CALL")
#undef MANGROVE_CALL

// src/mangrove/config/config.hpp.in
#pragma push_macro("MANGROVE_INLINE_NAMESPACE_BEGIN")
#undef MANGROVE_INLINE_NAMESPACE_BEGIN
#pragma push_macro("MANGROVE_INLINE_NAMESPACE_END")
#undef MANGROVE_INLINE_NAMESPACE_END

// src/mangrove/config/version.hpp.in
#pragma push_macro("MANGROVE_VERSION_EXTRA")
#undef MANGROVE_VERSION_EXTRA
#pragma push_macro("MANGROVE_VERSION_MAJOR")
#undef MANGROVE_VERSION_MAJOR
#pragma push_macro("MANGROVE_VERSION_MINOR")
#undef MANGROVE_VERSION_MINOR
#pragma push_macro("MANGROVE_VERSION_PATCH")
#undef MANGROVE_VERSION_PATCH

// export.hpp (generated by cmake)
#pragma push_macro("MANGROVE_API_H")
#undef MANGROVE_API_H
#pragma push_macro("MANGROVE_API")
#undef MANGROVE_API
#pragma push_macro("MANGROVE_PRIVATE")
#undef MANGROVE_PRIVATE
#pragma push_macro("MANGROVE_DEPRECATED")
#undef MANGROVE_DEPRECATED
#pragma push_macro("MANGROVE_DEPRECATED_EXPORT")
#undef MANGROVE_DEPRECATED_EXPORT
#pragma push_macro("MANGROVE_DEPRECATED_NO_EXPORT")
#undef MANGROVE_DEPRECATED_NO_EXPORT
#pragma push_macro("DEFINE_NO_DEPRECATED")
#undef DEFINE_NO_DEPRECATED
#pragma push_macro("MANGROVE_NO_DEPRECATED")
#undef MANGROVE_NO_DEPRECATED

#include <mangrove/config/compiler.hpp>
#include <mangrove/config/config.hpp>
#include <mangrove/config/export.hpp>
#include <mangrove/config/version.hpp>

#pragma push_macro("MANGROVE_UNREACHABLE")
#undef MANGROVE_UNREACHABLE
#define MANGROVE_UNREACHABLE std::abort()
