// Copyright 2016 MongoDB Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// src/mongo_odm/config/compiler.hpp
#undef MONGO_ODM_INLINE
#pragma pop_macro("MONGO_ODM_INLINE")
#if defined(_MSC_VER)
#pragma warning(pop)
#endif
#undef MONGO_ODM_CALL
#pragma pop_macro("MONGO_ODM_CALL")

// src/mongo_odm/config/config.hpp.in
#undef MONGO_ODM_INLINE_NAMESPACE_BEGIN
#pragma pop_macro("MONGO_ODM_INLINE_NAMESPACE_BEGIN")
#undef MONGO_ODM_INLINE_NAMESPACE_END
#pragma pop_macro("MONGO_ODM_INLINE_NAMESPACE_END")

// src/mongo_odm/config/version.hpp.in
#undef MONGO_ODM_VERSION_EXTRA
#pragma pop_macro("MONGO_ODM_VERSION_EXTRA")
#undef MONGO_ODM_VERSION_MAJOR
#pragma pop_macro("MONGO_ODM_VERSION_MAJOR")
#undef MONGO_ODM_VERSION_MINOR
#pragma pop_macro("MONGO_ODM_VERSION_MINOR")
#undef MONGO_ODM_VERSION_PATCH
#pragma pop_macro("MONGO_ODM_VERSION_PATCH")

// export.hpp (generated by cmake)
#undef MONGO_ODM_API_H
#pragma pop_macro("MONGO_ODM_API_H")
#undef MONGO_ODM_API
#pragma pop_macro("MONGO_ODM_API")
#undef MONGO_ODM_PRIVATE
#pragma pop_macro("MONGO_ODM_PRIVATE")
#undef MONGO_ODM_DEPRECATED
#pragma pop_macro("MONGO_ODM_DEPRECATED")
#undef MONGO_ODM_DEPRECATED_EXPORT
#pragma pop_macro("MONGO_ODM_DEPRECATED_EXPORT")
#undef MONGO_ODM_DEPRECATED_NO_EXPORT
#pragma pop_macro("MONGO_ODM_DEPRECATED_NO_EXPORT")
#undef DEFINE_NO_DEPRECATED
#pragma pop_macro("DEFINE_NO_DEPRECATED")
#undef MONGO_ODM_NO_DEPRECATED
#pragma pop_macro("MONGO_ODM_NO_DEPRECATED")

// prelude.hpp
#undef MONGO_ODM_UNREACHABLE
#pragma pop_macro("MONGO_ODM_UNREACHABLE")
