// Copyright 2016 MongoDB Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// src/mongo_odm/config/compiler.hpp
#pragma push_macro("MONGO_ODM_INLINE")
#undef MONGO_ODM_INLINE
#pragma push_macro("MONGO_ODM_CALL")
#undef MONGO_ODM_CALL

// src/mongo_odm/config/config.hpp.in
#pragma push_macro("MONGO_ODM_INLINE_NAMESPACE_BEGIN")
#undef MONGO_ODM_INLINE_NAMESPACE_BEGIN
#pragma push_macro("MONGO_ODM_INLINE_NAMESPACE_END")
#undef MONGO_ODM_INLINE_NAMESPACE_END

// src/mongo_odm/config/version.hpp.in
#pragma push_macro("MONGO_ODM_VERSION_EXTRA")
#undef MONGO_ODM_VERSION_EXTRA
#pragma push_macro("MONGO_ODM_VERSION_MAJOR")
#undef MONGO_ODM_VERSION_MAJOR
#pragma push_macro("MONGO_ODM_VERSION_MINOR")
#undef MONGO_ODM_VERSION_MINOR
#pragma push_macro("MONGO_ODM_VERSION_PATCH")
#undef MONGO_ODM_VERSION_PATCH

// export.hpp (generated by cmake)
#pragma push_macro("MONGO_ODM_API_H")
#undef MONGO_ODM_API_H
#pragma push_macro("MONGO_ODM_API")
#undef MONGO_ODM_API
#pragma push_macro("MONGO_ODM_PRIVATE")
#undef MONGO_ODM_PRIVATE
#pragma push_macro("MONGO_ODM_DEPRECATED")
#undef MONGO_ODM_DEPRECATED
#pragma push_macro("MONGO_ODM_DEPRECATED_EXPORT")
#undef MONGO_ODM_DEPRECATED_EXPORT
#pragma push_macro("MONGO_ODM_DEPRECATED_NO_EXPORT")
#undef MONGO_ODM_DEPRECATED_NO_EXPORT
#pragma push_macro("DEFINE_NO_DEPRECATED")
#undef DEFINE_NO_DEPRECATED
#pragma push_macro("MONGO_ODM_NO_DEPRECATED")
#undef MONGO_ODM_NO_DEPRECATED

#include <mongo_odm/config/compiler.hpp>
#include <mongo_odm/config/config.hpp>
#include <mongo_odm/config/export.hpp>
#include <mongo_odm/config/version.hpp>

#pragma push_macro("MONGO_ODM_UNREACHABLE")
#undef MONGO_ODM_UNREACHABLE
#define MONGO_ODM_UNREACHABLE std::abort()
