// Copyright 2016 MongoDB Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include <mangrove/config/prelude.hpp>

#define MANGROVE_PASTE_IMPL(s1, s2) s1##s2
#define MANGROVE_PASTE(s1, s2) MANGROVE_PASTE_IMPL(s1, s2)

// Wrap a field name to create a corresponding NVP
#define MANGROVE_NVP(x) mangrove::make_nvp(&mangrove_wrap_base::x, #x)

// Macro for creating custom field name
#define MANGROVE_CUSTOM_NVP(x, name) mangrove::make_nvp(&mangrove_wrap_base::x, name)

// Creates serialize() function
#define MANGROVE_SERIALIZE_KEYS                                                                   \
    template <class Archive>                                                                      \
    void serialize(Archive& ar) {                                                                 \
        mangrove_serialize_recur<Archive, 0,                                                      \
                                 std::tuple_size<decltype(mangrove_mapped_fields())>::value>(ar); \
    }                                                                                             \
    template <class Archive, size_t I, size_t N>                                                  \
    std::enable_if_t<(I < N), void> mangrove_serialize_recur(Archive& ar) {                       \
        auto nvp = std::get<I>(mangrove_mapped_fields());                                         \
        ar(cereal::make_nvp(nvp.name, this->*(nvp.t)));                                           \
        mangrove_serialize_recur<Archive, I + 1, N>(ar);                                          \
    }                                                                                             \
                                                                                                  \
    template <class Archive, size_t I, size_t N>                                                  \
    std::enable_if_t<(I == N), void> mangrove_serialize_recur(Archive&) {                         \
        ;                                                                                         \
    }

// Register members and create serialize() function
#define MANGROVE_MAKE_KEYS(Base, ...)                \
    using mangrove_wrap_base = Base;                 \
    constexpr static auto mangrove_mapped_fields() { \
        return std::make_tuple(__VA_ARGS__);         \
    }                                                \
    MANGROVE_SERIALIZE_KEYS

// If using the mangrove::model, then also register _id as a field.
#define MANGROVE_MAKE_KEYS_MODEL(Base, ...) MANGROVE_MAKE_KEYS(Base, MANGROVE_NVP(_id), __VA_ARGS__)

#define MANGROVE_KEY(value) mangrove::hasCallIfFieldIsPresent<decltype(&value), &value>::call()
// convenience macro for accessing scalar elements of array fields in query builder.
#define MANGROVE_ELEM(value) MANGROVE_KEY(value).element()

#define MANGROVE_KEY_BY_VALUE(value) \
    mangrove::hasCallIfFieldIsPresent<decltype(value), value>::call()

// MANGROVE_CHILD* macros, autogenerated to 100 levels (maximum BSON depth)
#include <mangrove/mangrove_child_autogen.hpp>

#define MANGROVE_CHILD(type, ...) \
    MANGROVE_PASTE(MANGROVE_CHILD, MANGROVE_PP_NARG(__VA_ARGS__))(type, __VA_ARGS__)

#define MANGROVE_CHILD_ELEM(...) MANGROVE_CHILD(__VA_ARGS__).element()

#include <mangrove/config/postlude.hpp>
