// Copyright 2016 MongoDB Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// src/boson/config/compiler.hpp
#undef BOSON_INLINE
#pragma pop_macro("BOSON_INLINE")
#if defined(_MSC_VER)
#pragma warning(pop)
#endif
#undef BOSON_CALL
#pragma pop_macro("BOSON_CALL")

// src/boson/config/config.hpp.in
#undef BOSON_INLINE_NAMESPACE_BEGIN
#pragma pop_macro("BOSON_INLINE_NAMESPACE_BEGIN")
#undef BOSON_INLINE_NAMESPACE_END
#pragma pop_macro("BOSON_INLINE_NAMESPACE_END")
#undef BOSON_POLY_USE_MNMLSTC
#pragma pop_macro("BOSON_POLY_USE_MNMLSTC")
#undef BOSON_POLY_USE_STD_EXPERIMENTAL
#pragma pop_macro("BOSON_POLY_USE_STD_EXPERIMENTAL")
#undef BOSON_POLY_USE_SYSTEM_MNMLSTC
#pragma pop_macro("BOSON_POLY_USE_SYSTEM_MNMLSTC")
#undef BOSON_POLY_USE_BOOST
#pragma pop_macro("BOSON_POLY_USE_BOOST")

// src/boson/config/version.hpp.in
#undef BOSON_VERSION_EXTRA
#pragma pop_macro("BOSON_VERSION_EXTRA")
#undef BOSON_VERSION_MAJOR
#pragma pop_macro("BOSON_VERSION_MAJOR")
#undef BOSON_VERSION_MINOR
#pragma pop_macro("BOSON_VERSION_MINOR")
#undef BOSON_VERSION_PATCH
#pragma pop_macro("BOSON_VERSION_PATCH")

// export.hpp (generated by cmake)
#undef BOSON_API_H
#pragma pop_macro("BOSON_API_H")
#undef BOSON_API
#pragma pop_macro("BOSON_API")
#undef BOSON_PRIVATE
#pragma pop_macro("BOSON_PRIVATE")
#undef BOSON_DEPRECATED
#pragma pop_macro("BOSON_DEPRECATED")
#undef BOSON_DEPRECATED_EXPORT
#pragma pop_macro("BOSON_DEPRECATED_EXPORT")
#undef BOSON_DEPRECATED_NO_EXPORT
#pragma pop_macro("BOSON_DEPRECATED_NO_EXPORT")
#undef DEFINE_NO_DEPRECATED
#pragma pop_macro("DEFINE_NO_DEPRECATED")
#undef BOSON_NO_DEPRECATED
#pragma pop_macro("BOSON_NO_DEPRECATED")

// prelude.hpp
#undef BOSON_UNREACHABLE
#pragma pop_macro("BOSON_UNREACHABLE")
