// Copyright 2016 MongoDB Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// src/boson/config/compiler.hpp
#pragma push_macro("BOSON_INLINE")
#undef BOSON_INLINE
#pragma push_macro("BOSON_CALL")
#undef BOSON_CALL

// src/boson/config/config.hpp.in
#pragma push_macro("BOSON_INLINE_NAMESPACE_BEGIN")
#undef BOSON_INLINE_NAMESPACE_BEGIN
#pragma push_macro("BOSON_INLINE_NAMESPACE_END")
#undef BOSON_INLINE_NAMESPACE_END
#pragma push_macro("BOSON_POLY_USE_MNMLSTC")
#undef BOSON_POLY_USE_MNMLSTC
#pragma push_macro("BOSON_POLY_USE_STD_EXPERIMENTAL")
#undef BOSON_POLY_USE_STD_EXPERIMENTAL
#pragma push_macro("BOSON_POLY_USE_SYSTEM_MNMLSTC")
#undef BOSON_POLY_USE_SYSTEM_MNMLSTC
#pragma push_macro("BOSON_POLY_USE_BOOST")
#undef BOSON_POLY_USE_BOOST

// src/boson/config/version.hpp.in
#pragma push_macro("BOSON_VERSION_EXTRA")
#undef BOSON_VERSION_EXTRA
#pragma push_macro("BOSON_VERSION_MAJOR")
#undef BOSON_VERSION_MAJOR
#pragma push_macro("BOSON_VERSION_MINOR")
#undef BOSON_VERSION_MINOR
#pragma push_macro("BOSON_VERSION_PATCH")
#undef BOSON_VERSION_PATCH

// export.hpp (generated by cmake)
#pragma push_macro("BOSON_API_H")
#undef BOSON_API_H
#pragma push_macro("BOSON_API")
#undef BOSON_API
#pragma push_macro("BOSON_PRIVATE")
#undef BOSON_PRIVATE
#pragma push_macro("BOSON_DEPRECATED")
#undef BOSON_DEPRECATED
#pragma push_macro("BOSON_DEPRECATED_EXPORT")
#undef BOSON_DEPRECATED_EXPORT
#pragma push_macro("BOSON_DEPRECATED_NO_EXPORT")
#undef BOSON_DEPRECATED_NO_EXPORT
#pragma push_macro("DEFINE_NO_DEPRECATED")
#undef DEFINE_NO_DEPRECATED
#pragma push_macro("BOSON_NO_DEPRECATED")
#undef BOSON_NO_DEPRECATED

#include <boson/config/compiler.hpp>
#include <boson/config/config.hpp>
#include <boson/config/export.hpp>
#include <boson/config/version.hpp>

#pragma push_macro("BOSON_UNREACHABLE")
#undef BOSON_UNREACHABLE
#define BOSON_UNREACHABLE std::abort()
