// Copyright 2014 MongoDB Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// src/bson_mapper/config/compiler.hpp
#undef BSON_MAPPER_INLINE
#pragma pop_macro("BSON_MAPPER_INLINE")
#if defined(_MSC_VER)
#pragma warning(pop)
#endif
#undef BSON_MAPPER_CALL
#pragma pop_macro("BSON_MAPPER_CALL")

// src/bson_mapper/config/config.hpp.in
#undef BSON_MAPPER_INLINE_NAMESPACE_BEGIN
#pragma pop_macro("BSON_MAPPER_INLINE_NAMESPACE_BEGIN")
#undef BSON_MAPPER_INLINE_NAMESPACE_END
#pragma pop_macro("BSON_MAPPER_INLINE_NAMESPACE_END")
#undef BSON_MAPPER_POLY_USE_MNMLSTC
#pragma pop_macro("BSON_MAPPER_POLY_USE_MNMLSTC")
#undef BSON_MAPPER_POLY_USE_STD_EXPERIMENTAL
#pragma pop_macro("BSON_MAPPER_POLY_USE_STD_EXPERIMENTAL")
#undef BSON_MAPPER_POLY_USE_SYSTEM_MNMLSTC
#pragma pop_macro("BSON_MAPPER_POLY_USE_SYSTEM_MNMLSTC")
#undef BSON_MAPPER_POLY_USE_BOOST
#pragma pop_macro("BSON_MAPPER_POLY_USE_BOOST")

// src/bson_mapper/config/version.hpp.in
#undef BSON_MAPPER_VERSION_EXTRA
#pragma pop_macro("BSON_MAPPER_VERSION_EXTRA")
#undef BSON_MAPPER_VERSION_MAJOR
#pragma pop_macro("BSON_MAPPER_VERSION_MAJOR")
#undef BSON_MAPPER_VERSION_MINOR
#pragma pop_macro("BSON_MAPPER_VERSION_MINOR")
#undef BSON_MAPPER_VERSION_PATCH
#pragma pop_macro("BSON_MAPPER_VERSION_PATCH")

// export.hpp (generated by cmake)
#undef BSON_MAPPER_API_H
#pragma pop_macro("BSON_MAPPER_API_H")
#undef BSON_MAPPER_API
#pragma pop_macro("BSON_MAPPER_API")
#undef BSON_MAPPER_PRIVATE
#pragma pop_macro("BSON_MAPPER_PRIVATE")
#undef BSON_MAPPER_DEPRECATED
#pragma pop_macro("BSON_MAPPER_DEPRECATED")
#undef BSON_MAPPER_DEPRECATED_EXPORT
#pragma pop_macro("BSON_MAPPER_DEPRECATED_EXPORT")
#undef BSON_MAPPER_DEPRECATED_NO_EXPORT
#pragma pop_macro("BSON_MAPPER_DEPRECATED_NO_EXPORT")
#undef DEFINE_NO_DEPRECATED
#pragma pop_macro("DEFINE_NO_DEPRECATED")
#undef BSON_MAPPER_NO_DEPRECATED
#pragma pop_macro("BSON_MAPPER_NO_DEPRECATED")

// prelude.hpp
#undef BSON_MAPPER_UNREACHABLE
#pragma pop_macro("BSON_MAPPER_UNREACHABLE")
