// Copyright 2014 MongoDB Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// src/bson_mapper/config/compiler.hpp
#pragma push_macro("BSON_MAPPER_INLINE")
#undef BSON_MAPPER_INLINE
#pragma push_macro("BSON_MAPPER_CALL")
#undef BSON_MAPPER_CALL

// src/bson_mapper/config/config.hpp.in
#pragma push_macro("BSON_MAPPER_INLINE_NAMESPACE_BEGIN")
#undef BSON_MAPPER_INLINE_NAMESPACE_BEGIN
#pragma push_macro("BSON_MAPPER_INLINE_NAMESPACE_END")
#undef BSON_MAPPER_INLINE_NAMESPACE_END
#pragma push_macro("BSON_MAPPER_POLY_USE_MNMLSTC")
#undef BSON_MAPPER_POLY_USE_MNMLSTC
#pragma push_macro("BSON_MAPPER_POLY_USE_STD_EXPERIMENTAL")
#undef BSON_MAPPER_POLY_USE_STD_EXPERIMENTAL
#pragma push_macro("BSON_MAPPER_POLY_USE_SYSTEM_MNMLSTC")
#undef BSON_MAPPER_POLY_USE_SYSTEM_MNMLSTC
#pragma push_macro("BSON_MAPPER_POLY_USE_BOOST")
#undef BSON_MAPPER_POLY_USE_BOOST

// src/bson_mapper/config/version.hpp.in
#pragma push_macro("BSON_MAPPER_VERSION_EXTRA")
#undef BSON_MAPPER_VERSION_EXTRA
#pragma push_macro("BSON_MAPPER_VERSION_MAJOR")
#undef BSON_MAPPER_VERSION_MAJOR
#pragma push_macro("BSON_MAPPER_VERSION_MINOR")
#undef BSON_MAPPER_VERSION_MINOR
#pragma push_macro("BSON_MAPPER_VERSION_PATCH")
#undef BSON_MAPPER_VERSION_PATCH

// export.hpp (generated by cmake)
#pragma push_macro("BSON_MAPPER_API_H")
#undef BSON_MAPPER_API_H
#pragma push_macro("BSON_MAPPER_API")
#undef BSON_MAPPER_API
#pragma push_macro("BSON_MAPPER_PRIVATE")
#undef BSON_MAPPER_PRIVATE
#pragma push_macro("BSON_MAPPER_DEPRECATED")
#undef BSON_MAPPER_DEPRECATED
#pragma push_macro("BSON_MAPPER_DEPRECATED_EXPORT")
#undef BSON_MAPPER_DEPRECATED_EXPORT
#pragma push_macro("BSON_MAPPER_DEPRECATED_NO_EXPORT")
#undef BSON_MAPPER_DEPRECATED_NO_EXPORT
#pragma push_macro("DEFINE_NO_DEPRECATED")
#undef DEFINE_NO_DEPRECATED
#pragma push_macro("BSON_MAPPER_NO_DEPRECATED")
#undef BSON_MAPPER_NO_DEPRECATED

#include <bson_mapper/config/config.hpp>
#include <bson_mapper/config/version.hpp>
#include <bson_mapper/config/export.hpp>
#include <bson_mapper/config/compiler.hpp>

#pragma push_macro("BSON_MAPPER_UNREACHABLE")
#undef BSON_MAPPER_UNREACHABLE
#define BSON_MAPPER_UNREACHABLE std::abort()
